language: python
python:
  - 3.7
install: 
  - pip install -r requirements.txt
script: python3 app.py || python app.py
deploy:
  provider: heroku
  api_key:
    secure: $heroku_key
  app:
    master: livability-qld
